### ISSUE TITLE
Fix versioning to be accepted into the Rack community repository

### ISSUE THREAD

**Issue by AndrewBelt** [jeremywen/JW-Modules#10]
Rack v0.5.1 will include a plugin manager, and plugins need to follow the [versioning guidelines](https://github.com/VCVRack/Rack/issues/266) in order to be accepted. You can use this [example plugin Makefile](https://github.com/VCVRack/Tutorial/blob/master/Makefile) and [Tutorial.cpp file](https://github.com/VCVRack/Tutorial/blob/master/src/Tutorial.cpp) as a reference for making sure the version is the same in the C++, Makefile, and JSON manifest.

- Your plugin has no version defined in a C++ file. You must set `plugin->version` using the Tutorial.cpp file as a reference.

Once you've fixed this, send a PR to the [Rack community repository](https://github.com/VCVRack/community) and remove the `"disabled"` property in the JSON manifest file if present.

**Comment by jeremywen** [comment]
should be fixed
