### ISSUE TITLE
Grid Seq Rnd Gates

### ISSUE THREAD

**Issue by briansorahan** [jeremywen/JW-Modules#12]
Thanks for the modules! I'm enjoying them.
I've noticed an issue with the gate buttons.
After I hit Rnd Gates it seems like the first click on a gate button that is off has no effect.
I'm on Rack 0.5.1 on Linux.

**Comment by jeremywen** [comment]
kinda funny but i think i finally fixed this 😆  it only took almost 3 years 😄

**Comment by jeremywen** [comment]
should be fixed - submitting to library

**Comment by briansorahan** [comment]
Thx @jeremywen !
