### ISSUE TITLE
Wav head Crash

### ISSUE THREAD

**Issue by Coirt** [jeremywen/JW-Modules#19]
Deleting wav head is causing a crash in Rack. Latest version, also tried it with a previous version.

**Comment by LKHSogpit** [comment]
And so does 0Cat. 

Is that thing supposed to remove all cables cause it sure does thanks for that! Messed up a 3 hour Patch.

**Comment by j4s0n-c** [comment]
+1. I just tried 0cat for the first time and it removed some cables from the modules near it. It did not crash Rack for me when I deleted it though.
