### ISSUE TITLE
Graphics glitching due to gridseq

### ISSUE THREAD

**Issue by qthegaijin** [jeremywen/JW-Modules#2]
On VCV v0.4.0 (havent tried latest dev build), MacOS

Noticed this today with a patch, the plug lights and graphics freeze temporarily and sporadically when gridseq is part of the patch. Sound is  not interupted, just graphics. This behavior was not present until the scale and random outputs were added.
Here is a screencap: https://www.dropbox.com/s/3kjyjln9y8rrnmx/GridSeq%20pauses.mov?dl=0

**Comment by jeremywen** [comment]
Can you try this one? https://github.com/jeremywen/JW-Modules/releases/tag/v0.4.4.1

**Comment by qthegaijin** [comment]
That seems to have resolved the issue! Works great now!

**Comment by jeremywen** [comment]
Awesome!  Sorry for the trouble!
