### ISSUE TITLE
Messed up coordinates system for CenteredLabel

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [jeremywen/JW-Modules#22]
I notice that [coordinates for layout out labels](https://github.com/jeremywen/JW-Modules/blob/master/src/GridSeq.cpp#L342-L348) don't match the coordinates used for placing Knobs, Inputs, etc. I've encountered the same annoyance in my code and was wondering if there was a better way.

**Comment by jeremywen** [comment]
any idea why my label uses a different coordinate system @AndrewBelt

**Comment by AndrewBelt** [comment]
The origin of a label is on its left baseline.

**Comment by jeremywen** [comment]
No the coordinate system is like mm or something

**Comment by WIZARDISHUNGRY** [comment]
I think we're doubling our coordinates for some reason.
