### ISSUE TITLE
NoteSEQ not available in windows version

### ISSUE THREAD

**Issue by F4Tornado** [jeremywen/JW-Modules#23]
I downloaded JW-Modules, hoping to use NoteSEQ on my windows computer, but it just doesn't show up in the menu.

**Comment by F4Tornado** [comment]
The release, not the source code

**Comment by jeremywen** [comment]
can you take a screenshot of the folder structure and files in your documents dir where you installed my modules?

**Comment by F4Tornado** [comment]
I think this might be a problem of VCV Rack, same thing happening with Bogaudio

**Comment by F4Tornado** [comment]
It seems like modules aren't updating when I download a newer version
