### ISSUE TITLE
Definition of RACK_DIR is missing from Makefile

### ISSUE THREAD

**Issue by cschol** [jeremywen/JW-Modules#24]
The `Makefile` should define a variable called `RACK_DIR`, which can be set to the location of the Rack source code. This allows compiling the plugin outside of the Rack source tree.

See [API Update Thread](https://github.com/VCVRack/Rack/issues/258#issuecomment-365346155).

**Comment by jeremywen** [comment]
mine is the same as the tutorial 
TUTORIAL https://github.com/VCVRack/Template/blob/master/Makefile#L24
MINE https://github.com/jeremywen/JW-Modules/blob/master/Makefile#L4

**Comment by cschol** [comment]
Oops, sorry. I didn't see the definition at the top. I'll check this again.

**Comment by cschol** [comment]
Ah, I see what's wrong. The variable is defined, but you are not using it.

YOURS:
```
include ../../plugin.mk
```

TUTORIAL:
```
include $(RACK_DIR)/plugin.mk
```

**Comment by jeremywen** [comment]
oops, thank you!  fixed.
