### ISSUE TITLE
Quantizer algorithm question

### ISSUE THREAD

**Issue by alto777** [jeremywen/JW-Modules#26]
hi JW!

I've been reading your code, you've got a lot of "how did he do that" stuff. Very educational!

While I was trying to be sure I can't use quantization, quite, in some of my creations, I took a close look at your quantization algorithm. The intervals it produces are a bit odd. By instrumentation as well as isolating the heart of your technique, I find that in an octave, the notes output enjoy different size slices of the 1 volt. For a C major scale, for example, the following widths are seen:

0.09 | C
0.17 | D
0.12  | E
0.12  | F
0.17  | G
0.17  | A
0.15  | B

I changed the code in quantizeutils.cpp like:

		for (int i = 1; i < notesInScale; i++) {
			scaleNoteInVolts = curScaleArr[i] / 12.0;
			if (scaleNoteInVolts > voltMinusOct) {
				closestVal =  curScaleArr[i - 1] / 12.0;
				break;
			}
			closestVal =  curScaleArr[i] / 12.0;
		}

which produces these widths:

0.17 | C
0.17 | D
0.08 | E
0.17 | F
0.16 | G
0.17 | A
0.07 | B

One could also imagine just cutting the one volt range into notesInScale number of same-sized "buckets". Here 0.143 volts each.

My sense is that there is no right or wrong, but I write to ask if this behaviour is what you intended and is it a synthesizer/quantizer general method, given that I did see it implemented elsewhere as you did it, with the same intervals/switching points.

My stuff just produces note numbers, it breaks the standard volt/octave model but I do all of that before output. It was in looking into providing a selection of scales that got me onto thinking I could just rely on someone's external quantizer. I don't think that will work, so I will have to bring the whole scale thing into my module.

a7

**Comment by jeremywen** [comment]
ya i think i am getting that last note wrong...  i will have to look into it someday...

**Comment by alto777** [comment]
I looked briefly at the section of code you had commented out regarding rounding to the next octave, which presumably would fix the first/last note.

I tried another approach, unfortunately _something_ I did overwrote my modification, but I believe it was as simple as making each scale one note longer and repeating the first note at octave + 1, like

	int SCALE_LOCRIAN        [8] = {0, 1, 3, 5, 6, 8, 10, 12};

and fixing any implications this caused, I do not remember that I had to do anything but change the arrays.

You may be amused by this quantizer:

http://www.bartonmusicalcircuits.com/uwq/

I have figured out most of how you did the labelled step scale select knob, so when you see something like that pop up on anything I do you will know where I ~~stole~~ got it from.
a7
