### ISSUE TITLE
Feature Request: Separate outputs for X and Y gates and...

### ISSUE THREAD

**Issue by killiun** [jeremywen/JW-Modules#3]
Grid Seq is great, thanks! I would love to have separate outputs for X and Y gates, the ablity to
skip steps and memorized coordinate sets similar to rene if possible.

**Comment by jeremywen** [comment]
1. "separate outputs for X and Y gates" means that as it is transitioning to the next row I would send a gate out the Y port, next column would be the x port?

2. skipping steps seems simple

3. oh you mean the snaking stuff, maybe, or maybe a different module someday.  I don't want to keep adding stuff.  Usually that means breaking other things and complexity.
