### ISSUE TITLE
NoteSeq locks Up

### ISSUE THREAD

**Issue by blackearth2014** [jeremywen/JW-Modules#32]
I am have major issues with the NoteSeq module. Every time I add it to a patch, less than 3 minutes later it causes a lock up on my laptop. I then have to reboot my system every time.

**Comment by jeremywen** [comment]
I can't reproduce this and nobody else has reported this.  Weird.

**Comment by blackearth2014** [comment]
I think it was my laptop not being able to handle vcvrack at the time I was
using it.
