### ISSUE TITLE
JW-Modules/plugin.dll: code 127

### ISSUE THREAD

**Issue by bobski70** [jeremywen/JW-Modules#34]
Hi JW,

In Win 10 , rack v 0.6c when I unzip your plugins to document\rack\plugins folder and start vcvrack I get error "could not load plugin \path to plugin" and in the log.txt the following is observed : Failed to load library C:\Users\myusername\Documents/Rack/plugins/JW-Modules/plugin.dll: code 127. 
Any idea how to solve this please ?
Regards

bob

**Comment by jeremywen** [comment]
I would use the plugin manager here https://vcvrack.com/plugins.html

**Comment by bobski70** [comment]
Hi JW,

Using plugin manager did the trick. Thank you very much.

Regards

Bob
________________________________
