### ISSUE TITLE
Feature request: Piano roll indicator NoteSeq

### ISSUE THREAD

**Issue by Coirt** [jeremywen/JW-Modules#36]
How would you feel about adding a darker colour to the grid on NoteSeq to indicate black keys or maybe changing the colour of the blue marker box for black keys? As is it's a little hard to figure where you are on the grid. Perhaps a small piano roll at the side.

![PianoRoll](https://user-images.githubusercontent.com/12150421/58375181-45153700-7f45-11e9-9d71-7991dbe963b5.JPG)

**Comment by Coirt** [comment]
Could probably do a better job here's a quick one. Makes it easier to lay notes out already.

![PianoRoll2](https://user-images.githubusercontent.com/12150421/58375292-3af43800-7f47-11e9-9ccd-848270db32af.JPG)

**Comment by jeremywen** [comment]
i like the look of this last screenshot but I don't know if I want to do that.  I don't really want it to look like a piano roll but I get the need.  I really like the more experimental functions, like random notes and shifting notes.  So I don't know maybe.  I don't think it would be a hard change, maybe only svg.
