### ISSUE TITLE
V1.0 NoteSeq 'Speed' Knob Is Broken

### ISSUE THREAD

**Issue by Chaircrusher** [jeremywen/JW-Modules#39]
If you try and turn the 'Speed' knob -- i.e. what controls the generation time in the Game of Life mode, it goes fully counterclockwise and won't move.

WORKAROUND: You can still set values if you right click on the knob and type in a value.

**Comment by jeremywen** [comment]
Was on vacation.  I see the same issue.  Looking into it now...

**Comment by jeremywen** [comment]
ok should be fixed in 1.0.3

**Comment by jeremywen** [comment]
also fixed #40
