### ISSUE TITLE
Fullscope no inputs

### ISSUE THREAD

**Issue by pippy900** [jeremywen/JW-Modules#4]
My Fullscope only has five knobs on the bottom right, to the left there are no inputs at all :( 

![fullscope no inputs](https://user-images.githubusercontent.com/33256720/32225930-01939952-be82-11e7-9eaf-f4f73f10618b.jpg)

**Comment by pippy900** [comment]
Disregard the second image.

**Comment by jeremywen** [comment]
Weird nobody else has had missing inputs there.  I would make sure everything is installed/reinstalled correctly and on the correct versions.

**Comment by pippy900** [comment]
It;s more than likely an installation error on my part, will update.
