### ISSUE TITLE
NoteSeq Crashes with V1.03

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [jeremywen/JW-Modules#40]
I can consistently get NoteSeq v1.03 to crash VCV Rack 1.1.1 by:

1, Load NoteSeq into a rack (doesn't even need to be connected to anything)
2. Draw a few random notes
3. Engage the Life button
4. Increase the speed knob

Result: within a second or two of playing with the speed knob, VCV Rack will crash to desktop.

Using Windows 10 x64, Windows MIDI, RME Fireface via ASIO in case any of that matters.

**Comment by jeremywen** [comment]
i am getting it too - looking into it...

**Comment by jeremywen** [comment]
ok found it - should be fixed next update

**Comment by jeremywen** [comment]
looks like 1.0.4 was just released to the PM :)
