### ISSUE TITLE
make in arch linux failed gsamplerate problem.

### ISSUE THREAD

**Issue by Malifick** [jeremywen/JW-Modules#5]
make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/BouncyBall.cpp.o src/BouncyBall.cpp
In file included from src/BouncyBall.cpp:2:0:
src/JWModules.hpp:27:7: warning: ‘virtual void FullScopeWidget::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/JWModules.hpp:28:10: warning: ‘virtual json_t* FullScopeWidget::toJson()’ can be marked override [-Wsuggest-override]
  json_t *toJson();
          ^~~~~~
src/JWModules.hpp:29:7: warning: ‘virtual void FullScopeWidget::fromJson(json_t*)’ can be marked override [-Wsuggest-override]
  void fromJson(json_t *rootJ);
       ^~~~~~~~
src/JWModules.hpp:40:8: warning: ‘virtual rack::Menu* GridSeqWidget::createContextMenu()’ can be marked override [-Wsuggest-override]
  Menu *createContextMenu();
        ^~~~~~~~~~~~~~~~~
src/JWModules.hpp:94:7: error: ‘void SmallWhiteKnob::onChange()’ marked ‘override’, but does not override
  void onChange() override {
       ^~~~~~~~
src/JWModules.hpp: In member function ‘void SmallWhiteKnob::onChange()’:
src/JWModules.hpp:95:23: error: no matching function for call to ‘SmallWhiteKnob::onChange()’
   RoundKnob::onChange();
                       ^
In file included from ../../include/gui.hpp:2:0,
                 from ../../include/rack.hpp:8,
                 from src/JWModules.hpp:1,
                 from src/BouncyBall.cpp:2:
../../include/app.hpp:219:7: note: candidate: virtual void rack::SVGKnob::onChange(rack::EventChange&)
  void onChange(EventChange &e) override;
       ^~~~~~~~
../../include/app.hpp:219:7: note:   candidate expects 1 argument, 0 provided
In file included from src/BouncyBall.cpp:2:0:
src/JWModules.hpp: At global scope:
src/JWModules.hpp:121:43: error: expected class-name before ‘{’ token
 struct MyBlueValueLight : ColorValueLight {
                                           ^
src/JWModules.hpp: In constructor ‘MyBlueValueLight::MyBlueValueLight()’:
src/JWModules.hpp:123:3: error: ‘baseColor’ was not declared in this scope
   baseColor = nvgRGB(25, 150, 252);
   ^~~~~~~~~
src/JWModules.hpp:123:3: note: suggested alternative: ‘bndTextColor’
   baseColor = nvgRGB(25, 150, 252);
   ^~~~~~~~~
   bndTextColor
src/BouncyBall.cpp: At global scope:
src/BouncyBall.cpp:31:7: warning: ‘virtual void BouncyBall::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/BouncyBall.cpp:32:7: error: virtual function ‘virtual void BouncyBall::initialize()’
  void initialize(){
       ^~~~~~~~~~
In file included from ../../include/rack.hpp:7:0,
                 from src/JWModules.hpp:1,
                 from src/BouncyBall.cpp:2:
../../include/engine.hpp:70:15: error: overriding final function ‘virtual void rack::Module::initialize()’
  virtual void initialize() final {}
               ^~~~~~~~~~
src/BouncyBall.cpp:32:7: warning: ‘virtual void BouncyBall::initialize()’ can be marked override [-Wsuggest-override]
  void initialize(){
       ^~~~~~~~~~
src/BouncyBall.cpp:36:10: warning: ‘virtual json_t* BouncyBall::toJson()’ can be marked override [-Wsuggest-override]
  json_t *toJson() {
          ^~~~~~
src/BouncyBall.cpp:41:7: warning: ‘virtual void BouncyBall::fromJson(json_t*)’ can be marked override [-Wsuggest-override]
  void fromJson(json_t *rootJ) {
       ^~~~~~~~
src/BouncyBall.cpp: In member function ‘virtual void BouncyBall::step()’:
src/BouncyBall.cpp:62:39: error: ‘gSampleRate’ was not declared in this scope
  bool pulse = gatePulse.process(1.0 / gSampleRate);
                                       ^~~~~~~~~~~
src/BouncyBall.cpp:62:39: note: suggested alternative: ‘glSampleMaski’
  bool pulse = gatePulse.process(1.0 / gSampleRate);
                                       ^~~~~~~~~~~
                                       glSampleMaski
src/BouncyBall.cpp: At global scope:
src/BouncyBall.cpp:89:7: warning: ‘virtual void BouncyBallDisplay::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
  void draw(NVGcontext *vg) {
       ^~~~
make: *** [../../compile.mk:54: build/src/BouncyBall.cpp.o] Error 1

**Comment by jeremywen** [comment]
my master branch is currently compiled against v0.4.  You are probably trying to compile against Rack master branch instead of the v0.4 tag.
