### ISSUE TITLE
NoteSeq lydian scale

### ISSUE THREAD

**Issue by bigblokemeds** [jeremywen/JW-Modules#53]
Hi Jeremy,
I've noticed that the lydian scale used by the NoteSeq sequencers isn't quite right, as it has a flat seventh instead of a major seventh. Not a huge issue, but slightly frustrating that the lydian mode isn't right on my favourite sequencer ever.

I love your stuff! helps make some great music.
Cheers

**Comment by jeremywen** [comment]
fixing next release
