### ISSUE TITLE
Uninitialized pointer in MinMax widget

### ISSUE THREAD

**Issue by stoermelder** [jeremywen/JW-Modules#61]
Hi Jeremy, I stumbled on an access to an uninitialized pointer in the MinMax module: `module` won't be initialized when the widget is rendered in the module browser.

https://github.com/jeremywen/JW-Modules/blob/3dfdfa5af979cb12f4121f148465cebe9d5ecaca/src/MinMax.cpp#L149-L150

**Comment by jeremywen** [comment]
but it doesn't error out because frame is zero, right?

**Comment by jeremywen** [comment]
does it only call draw once?

**Comment by stoermelder** [comment]
Hm, yes, you're right. 
I implemented an alternative module browser which allows resizing the previews and I noticed the crashes while changing the preview size while the browser is open. Everytime the size is changed `draw` is called again.
You can try it here if you like: https://github.com/stoermelder/vcvrack-packtau/releases/tag/Nightly

**Comment by jeremywen** [comment]
ah yes i tried that out with the v0.6 mode because i love favorites, but i also love the previews, so oh well - i can add a simple check for my next update if that helps you

**Comment by stoermelder** [comment]
Yes that would be great, thanks!

**Comment by jeremywen** [comment]
fix is released
