### ISSUE TITLE
After randomizing gates Grid Seq Gates on/off work weird

### ISSUE THREAD

**Issue by Petervos2018** [jeremywen/JW-Modules#62]
You need to double-click to turn them on again.
Off still works as expected, and once you turned them on they also work as expected.
W10  JW v1.0.12

Greetings Peter.

Also mentioned here : https://www.facebook.com/groups/vcvrack/?post_id=608543173139164&comment_id=612123172781164

**Comment by jeremywen** [comment]
ya i looked into it a little and fixed one thing after my latest release but i don’t think its all the way fix yet - also apparently been there a while #12 🤣

**Comment by Petervos2018** [comment]
Yeh, it's an oldie but a goodie (had not seen #12 )

**Comment by jeremywen** [comment]
ok just pushed up a fix - let me know if you can build or need a mac build

**Comment by jeremywen** [comment]
should be fixed - submitting to library
