### ISSUE TITLE
Bouncy Ball

### ISSUE THREAD

**Issue by sebastien-bouffier** [jeremywen/JW-Modules#7]
Hello Jeremy,
First, "bravo" and thanks for your great modules.
I am in touch with "phdsg" who asks me to think about a module based on physics.
Since I made a module ChUTE which is a trigger based on a "bouncing ball" movement he thinks, and it makes sense, that I could do something like that [carambolage]( https://github.com/sebastien-bouffier/Bidoo/issues/7)
I have seen in your repository that you launched BouncyBall.cpp.
Is it something that you will push in that direction ?
Best,

**Comment by jeremywen** [comment]
I didn't really answer your question.  Yes, it will do something like that.  Different gate outs, speed, triggers to start a new ball.  Not sure yet where it will go...

**Comment by sebastien-bouffier** [comment]
Ok great. 
Regarding the settling of the ball, it was one of the 2 goals of ChUTE. I wanted to make a trigger that can go from unusual but musical swings to crazy trigs "à la" bucephalus from Aphex.
