### ISSUE TITLE
DIVSEQ - Hitting reset removes generated patterns from pressed berofe random buttons

### ISSUE THREAD

**Issue by vcvrackideas** [jeremywen/JW-Modules#75]
Hi Jeremy. Just recorded some kind of patch from scratch video tutorial and saw that strange behaviour when sending resets. It just removing previously generated gates (at least as I tried) via random buttons. Not sure that is how it's supposed to work. Cheers!
Thanks for making that module by the way! A must have for nice not annoying sequences!

**Comment by jeremywen** [comment]
can you explain how to reproduce it?

**Comment by vcvrackideas** [comment]
[jw divseq bug.zip](https://github.com/jeremywen/JW-Modules/files/6446145/jw.divseq.bug.zip)
ok here is the patch where I just press Random - Gate button. Now if you apply a reset trigger from CLKD the all gate should be in initial state

**Comment by jeremywen** [comment]
oh I think I see what you mean... it is turning all the gates on when you hit reset, but it should not change gate state on reset, right?

**Comment by jeremywen** [comment]
i found the bug, fixing

**Comment by jeremywen** [comment]
fix should now bee released
