### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [jeremywen/JW-Modules#80]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example:
```
MinMaxDisplay() {
   font = APP->window->loadFont(asset::plugin(pluginInstance, "res/DejaVuSansMono.ttf"));
}    
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by jeremywen** [comment]
sorry fixed by https://github.com/jeremywen/JW-Modules/commit/68f04a5a8a1a656e7a3aa7e217524f0feb91167e
