### ISSUE TITLE
Issues entering notes in the NoteSeq modules

### ISSUE THREAD

**Issue by GrayCatMusic** [jeremywen/JW-Modules#83]
Hi Jeremy,
Thank you as always for the wonderful modules. In Rack Pro 2.0.6, all of the NoteSeq modules have a small problem where the cells fill up faster than the mouse can get there. For example, if you click and drag in a straight line, the line fills up before the mouse finishes reaching the end. It happens in Patterns & Trigs as well, any module with the grid for notes. If it's not something that you can replicate, I'll provide a video and my system specs and anything else you need. Otherwise the modules work great. Thanks!
~Kyle

**Comment by GrayCatMusic** [comment]
I just checked and you are correct, at 100% they all behave as expected. And then if you zoom out more, the inverse happens and the notes can't keep up with the mouse.

**Comment by jeremywen** [comment]
should be fixed now in the latest release
